import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { CssBaseline, ThemeProvider } from '@mui/material';
import sisTheme from '@/styles/theme';
import '@/styles/globals.css';
import { RouterProvider } from '@tanstack/react-router';
import { router } from './router';
import { AuthProvider } from '@auth/AuthContext';
const qc = new QueryClient();
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsxs(ThemeProvider, { theme: sisTheme, children: [_jsx(CssBaseline, {}), _jsx(QueryClientProvider, { client: qc, children: _jsx(AuthProvider, { children: _jsx(RouterProvider, { router: router }) }) })] }) }));
